"""added race table

Revision ID: 03ecf8fce8ce
Revises: 2cedbc8a71e9
Create Date: 2025-12-21 11:36:37.922570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ecf8fce8ce'
down_revision: Union[str, Sequence[str], None] = '2cedbc8a71e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ground_race',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bucket_model', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['datalake.person_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='datalake'
    )
    op.create_index('ix_ground_race_bucket_model', 'ground_race', ['bucket_model'], unique=False, schema='datalake')
    op.create_index('ix_ground_race_person_id', 'ground_race', ['person_id'], unique=False, schema='datalake')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ground_race_person_id', table_name='ground_race', schema='datalake')
    op.drop_index('ix_ground_race_bucket_model', table_name='ground_race', schema='datalake')
    op.drop_table('ground_race', schema='datalake')
    # ### end Alembic commands ###
