"""move tables to datalake

Revision ID: 1b1e638608c7
Revises: f34e536f97b0
Create Date: 2025-11-08 10:43:33.786092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b1e638608c7'
down_revision: Union[str, Sequence[str], None] = 'f34e536f97b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voter_file',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='datalake'
    )
    op.create_index('ix_voter_file_received_at', 'voter_file', ['received_at'], unique=False, schema='datalake')
    op.create_table('voter_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('street_number', sa.Text(), nullable=True),
    sa.Column('street_name', sa.Text(), nullable=True),
    sa.Column('municipality', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip5', sa.String(length=5), nullable=True),
    sa.Column('name_canonical', sa.Text(), nullable=False),
    sa.Column('address_canonical', sa.Text(), nullable=False),
    sa.Column('name_hash', sa.String(length=64), nullable=False),
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['datalake.voter_file.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='datalake'
    )
    op.create_index('ix_voter_record_address_hash', 'voter_record', ['address_hash'], unique=False, schema='datalake')
    op.create_index('ix_voter_record_file_id', 'voter_record', ['file_id'], unique=False, schema='datalake')
    op.create_index('ix_voter_record_municipality', 'voter_record', ['municipality'], unique=False, schema='datalake')
    op.create_index('ix_voter_record_name_hash', 'voter_record', ['name_hash'], unique=False, schema='datalake')
    op.create_index('ix_voter_record_state', 'voter_record', ['state'], unique=False, schema='datalake')
    op.create_index('ix_voter_record_zip5', 'voter_record', ['zip5'], unique=False, schema='datalake')
    op.create_table('voter_geocode',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('benchmark', sa.Text(), nullable=False),
    sa.Column('vintage', sa.Text(), nullable=False),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['datalake.voter_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', 'benchmark', 'vintage'),
    schema='datalake'
    )
    op.create_index('ix_voter_geocode_combo', 'voter_geocode', ['benchmark', 'vintage'], unique=False, schema='datalake')
    op.create_index('ix_voter_geocode_geoid', 'voter_geocode', ['geoid'], unique=False, schema='datalake')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voter_geocode_geoid', table_name='voter_geocode', schema='datalake')
    op.drop_index('ix_voter_geocode_combo', table_name='voter_geocode', schema='datalake')
    op.drop_table('voter_geocode', schema='datalake')
    op.drop_index('ix_voter_record_zip5', table_name='voter_record', schema='datalake')
    op.drop_index('ix_voter_record_state', table_name='voter_record', schema='datalake')
    op.drop_index('ix_voter_record_name_hash', table_name='voter_record', schema='datalake')
    op.drop_index('ix_voter_record_municipality', table_name='voter_record', schema='datalake')
    op.drop_index('ix_voter_record_file_id', table_name='voter_record', schema='datalake')
    op.drop_index('ix_voter_record_address_hash', table_name='voter_record', schema='datalake')
    op.drop_table('voter_record', schema='datalake')
    op.drop_index('ix_voter_file_received_at', table_name='voter_file', schema='datalake')
    op.drop_table('voter_file', schema='datalake')
    # ### end Alembic commands ###
