"""Replace voter_* with data_file/person_record/census_geocode/other_geocode

Revision ID: 7d9884be020c
Revises: 27ee4ac853d0
Create Date: 2025-11-23 08:33:01.027404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d9884be020c'
down_revision: Union[str, Sequence[str], None] = '27ee4ac853d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_file',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256'),
    schema='datalake'
    )
    op.create_index('ix_data_file_received_at', 'data_file', ['received_at'], unique=False, schema='datalake')
    op.create_table('person_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('street_number', sa.Text(), nullable=True),
    sa.Column('street_name', sa.Text(), nullable=True),
    sa.Column('municipality', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip5', sa.String(length=5), nullable=True),
    sa.Column('name_canonical', sa.Text(), nullable=False),
    sa.Column('address_canonical', sa.Text(), nullable=False),
    sa.Column('name_hash', sa.String(length=64), nullable=False),
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['datalake.data_file.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='datalake'
    )
    op.create_index('ix_person_record_address_hash', 'person_record', ['address_hash'], unique=False, schema='datalake')
    op.create_index('ix_person_record_file_id', 'person_record', ['file_id'], unique=False, schema='datalake')
    op.create_index('ix_person_record_municipality', 'person_record', ['municipality'], unique=False, schema='datalake')
    op.create_index('ix_person_record_name_hash', 'person_record', ['name_hash'], unique=False, schema='datalake')
    op.create_index('ix_person_record_state', 'person_record', ['state'], unique=False, schema='datalake')
    op.create_index('ix_person_record_zip5', 'person_record', ['zip5'], unique=False, schema='datalake')
    op.create_table('census_geocode',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('benchmark', sa.Text(), nullable=False),
    sa.Column('vintage', sa.Text(), nullable=False),
    sa.Column('geoid', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['datalake.person_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id', 'benchmark', 'vintage'),
    schema='datalake'
    )
    op.create_index('ix_census_geocode_combo', 'census_geocode', ['benchmark', 'vintage'], unique=False, schema='datalake')
    op.create_index('ix_census_geocode_geoid', 'census_geocode', ['geoid'], unique=False, schema='datalake')
    op.create_table('other_geocode',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['datalake.person_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='datalake'
    )
    op.create_index('ix_other_geocode_record_id', 'other_geocode', ['record_id'], unique=False, schema='datalake')
    op.create_index('ix_other_geocode_status', 'other_geocode', ['status'], unique=False, schema='datalake')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_other_geocode_status', table_name='other_geocode', schema='datalake')
    op.drop_index('ix_other_geocode_record_id', table_name='other_geocode', schema='datalake')
    op.drop_table('other_geocode', schema='datalake')
    op.drop_index('ix_census_geocode_geoid', table_name='census_geocode', schema='datalake')
    op.drop_index('ix_census_geocode_combo', table_name='census_geocode', schema='datalake')
    op.drop_table('census_geocode', schema='datalake')
    op.drop_index('ix_person_record_zip5', table_name='person_record', schema='datalake')
    op.drop_index('ix_person_record_state', table_name='person_record', schema='datalake')
    op.drop_index('ix_person_record_name_hash', table_name='person_record', schema='datalake')
    op.drop_index('ix_person_record_municipality', table_name='person_record', schema='datalake')
    op.drop_index('ix_person_record_file_id', table_name='person_record', schema='datalake')
    op.drop_index('ix_person_record_address_hash', table_name='person_record', schema='datalake')
    op.drop_table('person_record', schema='datalake')
    op.drop_index('ix_data_file_received_at', table_name='data_file', schema='datalake')
    op.drop_table('data_file', schema='datalake')
    # ### end Alembic commands ###
