"""added address table

Revision ID: f00dc88e1772
Revises: 5b8fabef956c
Create Date: 2025-12-02 08:16:51.900332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00dc88e1772'
down_revision: Union[str, Sequence[str], None] = '5b8fabef956c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_hash', sa.String(length=64), nullable=False),
    sa.Column('address_canonical', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('address_hash'),
    schema='datalake'
    )
    op.create_index('ix_address_canonical', 'address', ['address_canonical'], unique=False, schema='datalake')
    op.add_column('census_geocode', sa.Column('id', sa.String(length=36), nullable=False), schema='datalake')
    op.add_column('census_geocode', sa.Column('address_hash', sa.String(length=64), nullable=False), schema='datalake')
    op.create_index('ix_census_geocode_addr', 'census_geocode', ['address_hash'], unique=False, schema='datalake')
    op.create_unique_constraint('uq_census_addr_bench_vint', 'census_geocode', ['address_hash', 'benchmark', 'vintage'], schema='datalake')
    op.drop_constraint(op.f('census_geocode_record_id_fkey'), 'census_geocode', schema='datalake', type_='foreignkey')
    op.create_foreign_key(None, 'census_geocode', 'address', ['address_hash'], ['address_hash'], source_schema='datalake', referent_schema='datalake', ondelete='CASCADE')
    op.drop_column('census_geocode', 'record_id', schema='datalake')
    op.add_column('other_geocode', sa.Column('address_hash', sa.String(length=64), nullable=False), schema='datalake')
    op.drop_index(op.f('ix_other_geocode_record_id'), table_name='other_geocode', schema='datalake')
    op.create_index('ix_other_geocode_addr', 'other_geocode', ['address_hash'], unique=False, schema='datalake')
    op.drop_constraint(op.f('other_geocode_record_id_fkey'), 'other_geocode', schema='datalake', type_='foreignkey')
    op.create_foreign_key(None, 'other_geocode', 'address', ['address_hash'], ['address_hash'], source_schema='datalake', referent_schema='datalake', ondelete='CASCADE')
    op.drop_column('other_geocode', 'record_id', schema='datalake')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('other_geocode', sa.Column('record_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False), schema='datalake')
    op.drop_constraint(None, 'other_geocode', schema='datalake', type_='foreignkey')
    op.create_foreign_key(op.f('other_geocode_record_id_fkey'), 'other_geocode', 'person_record', ['record_id'], ['id'], source_schema='datalake', referent_schema='datalake', ondelete='CASCADE')
    op.drop_index('ix_other_geocode_addr', table_name='other_geocode', schema='datalake')
    op.create_index(op.f('ix_other_geocode_record_id'), 'other_geocode', ['record_id'], unique=False, schema='datalake')
    op.drop_column('other_geocode', 'address_hash', schema='datalake')
    op.add_column('census_geocode', sa.Column('record_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False), schema='datalake')
    op.drop_constraint(None, 'census_geocode', schema='datalake', type_='foreignkey')
    op.create_foreign_key(op.f('census_geocode_record_id_fkey'), 'census_geocode', 'person_record', ['record_id'], ['id'], source_schema='datalake', referent_schema='datalake', ondelete='CASCADE')
    op.drop_constraint('uq_census_addr_bench_vint', 'census_geocode', schema='datalake', type_='unique')
    op.drop_index('ix_census_geocode_addr', table_name='census_geocode', schema='datalake')
    op.drop_column('census_geocode', 'address_hash', schema='datalake')
    op.drop_column('census_geocode', 'id', schema='datalake')
    op.drop_index('ix_address_canonical', table_name='address', schema='datalake')
    op.drop_table('address', schema='datalake')
    # ### end Alembic commands ###
